# Generated by Django 3.0.2 on 2020-01-23 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 22, 55, 19, 40315)),
        ),
    ]
