# Generated by Django 3.0.2 on 2020-01-17 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200117_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 22, 3, 30, 432970)),
        ),
    ]
